### ISSUE TITLE
为什么默认情况下不启动ProxySetter插件

### ISSUE THREAD

**Issue by wajika** [vrnobody/V2RayGCon#1]
我纳闷了一会儿，为什么开启后图标依然没有变色，原来必须要启动ProxySetter插件，这么关键的信息怎么没有明显提示呢？默认情况下这个插件还是关闭的。

另外提个小建议 开始和停止这种最常用的按钮应该设计一个独立的并且放在最明显的位置。

**Comment by wajika** [comment]
还有个问题，启动后网页打开速度比v2rayN慢很多

**Comment by wajika** [comment]
还有个问题，启动后网页打开速度比v2rayN慢很多

**Comment by vrnobody** [comment]
将在下个版本默认开启ProxySetter插件。

独立是指整个界面只有一组开始/停止？那样不知道对应哪个服务器啊。
如果是开始/停止选中的多个服务器，这个功能不太常用，所以没把图标放出来。

速度问题如果只是开启PAC后慢，那么使自定义PAC吧，毕竟每个人常去的网站并不相同。
如果不开PAC也慢，那么就是v2ray-core那边的问题了。
这个软件是直接用v2ray-core的http/socks inbound，没有加其他中间件。

**Comment by wajika** [comment]
@vrnobody 有没有别的方法自动配置代理？ 就像影梭那种。
我看了一下大部分的工具按钮都是以最后一次的选择记录为准

**Comment by vrnobody** [comment]
SS我没怎么用，不太明白自动是指什么。

**Comment by wajika** [comment]
@vrnobody 其实我的意思是设计的更简单，更傻瓜，操作步骤越少越好
