### ISSUE TITLE
为什么Inbound的port非要强制8080？

### ISSUE THREAD

**Issue by 3zhang** [vrnobody/V2RayGCon#10]
莫名其妙的 本来以前的版本挺好的 配置都能自己调 这么不自由还怎么用...

**Comment by 3zhang** [comment]
最终配置想改还改不了 无语

**Comment by vrnobody** [comment]
没有强制8080啊，可以在“选项”->"默认值“ -> "导入分享链接"中修改inbound的协议、端口等。
”查看最终配置“是只读的不能修改，已经导入的配置要用"Json编辑器"修改。
如果某个服务器比较特殊，自行修改完配置后，点下”h8080"蓝色标签，在“*inbound”选"Config"你的配置就会原封不动的传给v2ray-core。

**Comment by vrnobody** [comment]
已更新相应文档 [自定义inbounds](https://vrnobody.github.io/V2RayGCon/01-usage/15-custom-inbounds/)
