### ISSUE TITLE
无法通过base64或者二维码导入inbounds

### ISSUE THREAD

**Issue by FavorMylikes** [vrnobody/V2RayGCon#17]
不支持v2ray协议

**Comment by vrnobody** [comment]
没看懂你遇到了什么问题？这个软件支持的分享链接有 [https://vrnobody.github.io/V2RayGCon/01-usage/16-share-links/](https://vrnobody.github.io/V2RayGCon/01-usage/16-share-links/) 这几种，所以只可以扫描这几种分享链接的二维码。而除v2cfg://...以外，其他分享链接都只包含第一个outbound的部分信息，不包含inbounds信息，所以导入时不会涉及到inbounds。订阅是简单的对上面那些分享链接进行base64编码，所以也不涉及inbounds。如果你希望新导入的服务器采用自己设定的inbounds，那么先在【选项-默认值-自定义inbounds】里面填好inbounds设置，然后【导入分享链接-默认模式】选【自定义】就可以。不支持v2ray协议具体是指什么？

**Comment by FavorMylikes** [comment]
@vrnobody 感谢回复

在`v2rayGCON v1.1`版本时，分享产生两个版本的base64协议，`v2ray://`和`vmess://`

其中`vmess://`仅包含`outbounds`相关信息

我已知通过`v2ray://`进行服务器分享

升级到1.5及以上后，无法使用该功能，即，我无法控制客户端应该使用的端口号，造成了一些重复性的配置工作

而`V2rayGCON v1.6`目前也无法通过分享配置，将自身的默认`inbounds`端口囊括进来，测试发现，目前只有[`import`, `subscription`, `servers`, `plugins`]4个字段。

**Comment by FavorMylikes** [comment]
这种场景出现在我需要给多个电脑配置客户端设置时出现

感谢你在`V2rayGCON`上的延续工作，但`V2rayN`目前做的更好一点

**Comment by vrnobody** [comment]
哇v1.1！！！那是好老的版本了。当时是因为v2ray-core那边提出[FOV001](https://github.com/v2ray/v2ray-core/issues/1569)的分享链接里面也是用v2ray://...开头，为了不产生冲突所以V2RayGCon的v2ray://...改名成v2cfg://...，它里面base64编码的内容是一样的。所以直接用记事本替换一下前面几个字母就可以导入了。不过当时用的好像还是v3.x配置格式，不知道现在v4.x的core还支不支持。现在用v2cfg://...效果是一样的，不过由于安全原因，不能扫码，只能在【主窗口-文件-从剪切板导入】。注意【选项-默认值-导入分享链接-默认模式】中要选Config，新导入链接的inbounds才生效。已经导入的服务器可以在【主窗口-服务器-批量修改】里面把inbound模式改成Config。

**Comment by vrnobody** [comment]
这里有inbound几种模式的说明：
[https://vrnobody.github.io/V2RayGCon/01-usage/15-custom-inbounds/](https://vrnobody.github.io/V2RayGCon/01-usage/15-custom-inbounds/)

**Comment by FavorMylikes** [comment]
原来如此，感谢提醒
