### ISSUE TITLE
最新版v1.6.7.0无法运行....

### ISSUE THREAD

**Issue by wxlg1117** [vrnobody/V2RayGCon#18]
奇怪,最新版v1.6.7.0在win7x64和windows server 2019上都是不能正常运行;
**上一版本[v1.6.6.0]没有问题.**

win7 x64 with .net framework 4.8.
![Snipaste_2023-01-05_13-48-52](https://user-images.githubusercontent.com/9752596/210711180-9bf4d2f5-1fe5-4fd8-9476-6083b0e5cf34.jpg)

windows事件查看器显示.
Application Error:
错误应用程序名称: V2RayGCon.exe，版本: 1.0.0.0，时间戳: 0x62bbc470
错误模块名称: KERNELBASE.dll，版本: 6.1.7601.24545，时间戳: 0x5e0eb6bd
异常代码: 0xe0434352
错误偏移量: 0x000000000000b87d
错误进程 ID: 0xf34
错误应用程序启动时间: 0x01d920c974776c7b
错误应用程序路径: C:\V2RayGCon\V2RayGCon.exe
错误模块路径: C:\Windows\system32\KERNELBASE.dll
报告 ID: b22e405a-8cbc-11ed-b0bc-5ee569a4c7d9

.NET Runtime:
应用程序: V2RayGCon.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.IO.FileNotFoundException
   在 V2RayGCon.Services.Settings.LoadUserSettingsFromFile()
   在 V2RayGCon.Services.Settings.LoadUserSettings()
   在 V2RayGCon.Services.Settings..ctor()

异常信息: System.Reflection.TargetInvocationException
   在 System.RuntimeTypeHandle.CreateInstance(System.RuntimeType, Boolean, Boolean, Boolean ByRef, System.RuntimeMethodHandleInternal ByRef, Boolean ByRef)
   在 System.RuntimeType.CreateInstanceSlow(Boolean, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   在 System.Activator.CreateInstance(System.Type, Boolean)
   在 V2RayGCon.BaseClasses.SingletonService`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CreateInstanceOfT()
   在 System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CreateValue()
   在 System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].LazyInitValue()
   在 V2RayGCon.Services.Launcher..ctor()
   在 V2RayGCon.Program.Main()

win 2019 with 4.8:

windows事件查看器显示.
Application Error:
错误应用程序名称: V2RayGCon.exe，版本: 1.0.0.0，时间戳: 0x62bbc470
错误模块名称: KERNELBASE.dll，版本: 10.0.17763.3770，时间戳: 0x03ee2fdb
异常代码: 0xe0434352
错误偏移量: 0x00000000000349d9
错误进程 ID: 0x1d14
错误应用程序启动时间: 0x01d920c9ae1c63ab
错误应用程序路径: C:\V2RayGCon-box\V2RayGCon.exe
错误模块路径: C:\Windows\System32\KERNELBASE.dll
报告 ID: 0eaa7b73-d9d5-4ced-ad61-8d342703afcf
错误程序包全名: 
错误程序包相对应用程序 ID: 

.NET Runtime:
应用程序: V2RayGCon.exe
Framework 版本: v4.0.30319
说明: 由于未经处理的异常，进程终止。
异常信息: System.IO.FileNotFoundException
   在 V2RayGCon.Services.Settings.LoadUserSettingsFromFile()
   在 V2RayGCon.Services.Settings.LoadUserSettings()
   在 V2RayGCon.Services.Settings..ctor()

异常信息: System.Reflection.TargetInvocationException
   在 System.RuntimeTypeHandle.CreateInstance(System.RuntimeType, Boolean, Boolean, Boolean ByRef, System.RuntimeMethodHandleInternal ByRef, Boolean ByRef)
   在 System.RuntimeType.CreateInstanceSlow(Boolean, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   在 System.Activator.CreateInstance(System.Type, Boolean)
   在 V2RayGCon.BaseClasses.SingletonService`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CreateInstanceOfT()
   在 System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CreateValue()
   在 System.Lazy`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].LazyInitValue()
   在 V2RayGCon.Services.Launcher..ctor()
   在 V2RayGCon.Program.Main()

**Comment by vrnobody** [comment]
谢谢反馈！！
竟然出这么大一个BUG，这么长时间都没发现，太过意不去了。
请测试下[V2RayGCon v1.6.7.4](https://github.com/vrnobody/V2RayGCon/releases/tag/1.6.7.4)

**Comment by wxlg1117** [comment]
> 谢谢反馈！！ 竟然出这么大一个BUG，这么长时间都没发现，太过意不去了。 请测试下[V2RayGCon v1.6.7.4](https://github.com/vrnobody/V2RayGCon/releases/tag/1.6.7.4)

新版本能正常运行了.
