### ISSUE TITLE
终端如何走代理

### ISSUE THREAD

**Issue by NameWjp** [vrnobody/V2RayGCon#24]
其他软件想走代理，一般要配置一个 http 和 socks 地址，但是我没找到在哪里配置。

**Comment by vrnobody** [comment]
这个取决于具体的命令行工具。如果命令行工具支持环境变量那么可以在终端设置环境变量。以wget.exe为例：
在cmd.exe里面可以`set "http_proxy=127.0.0.1:8080" && set "https_proxy=127.0.0.1:8080"`
在msys2里面可以`export http_proxy=http://127.0.0.1:8080; export https_proxy=http://127.0.0.1:8080`
PowerShell我没怎么用，不太清楚。

不支持环境变量的命令行工具，可以试下ProxySetter插件的tun模式。

这两都搞不定的话，我能想到只有软路由了，但是这超出这个软件的能力范围了。

**Comment by NameWjp** [comment]
这里的 8080 端口有地方配置么，还是说定死的。

**Comment by vrnobody** [comment]
可以修改，点下服务器左下角浅蓝色的"http"标签，然后修改"*inbound"。
具体看 https://vrnobody.github.io/V2RayGCon/01-usage/15-custom-inbounds/ 里面的第三张图。

**Comment by NameWjp** [comment]
@vrnobody 感谢！
