### ISSUE TITLE
界面調整需求

### ISSUE THREAD

**Issue by La-Hire** [vrnobody/V2RayGCon#3]
節點名称比较长情況下，不能完整顯示該節點具體信息
如
XXX中转---某地----XX倍率
会显示为
[XXX中转-...]
可否考虑調整每個服務器的名稱顯示，當不足時自動換行，保證節點名稱顯示完全

**Comment by vrnobody** [comment]
自动换行需要调整服务器面板的高度，这会影响主窗口的总高度，不太合适。
如果名称显示一行，协议等摘要信息再显示一行，名字很短的服务器又会很难看。

暂时改成在Tooltip中分两行显示服务器名和摘要。
