### ISSUE TITLE
删除订阅时可以一起删除来自订阅地址的链接吗？

### ISSUE THREAD

**Issue by wajika** [vrnobody/V2RayGCon#4]
来自订阅的链接，在删除订阅地址时可以一起被删除
另外有没有办法批量删除拥有某一个名字特征的链接

**Comment by vrnobody** [comment]
一.删除订阅
添加订阅的时候注意设定一个容易区分的别名,然后在主窗口搜索那个别名
接着点"选择"-"全部页面"-"全选"
然后点"服务器"-"删除选中的服务器"

二.批量删除
如果名字短可以用和订阅相同的方法,搜索后全选删除
如果名字太长就需要在Luna插件里写脚本
大概像这样:
```lua
for coreServ in Each(Server:GetAllServers()) do
    local coreState = coreServ:GetCoreStates()
    local name = coreState:GetName()
    -- 添加你要对 name 作什么操作的代码
    print(name)
end
```
[Luna插件详细说明](https://vrnobody.github.io/V2RayGCon/03-plugins/01-luna/)  

  
  
因为删除容易误伤,所以不打算添加过于自动化的删除功能

**Comment by wajika** [comment]
@vrnobody 
看来你遇到bug了,请将以下内容发给作者。

System.InvalidOperationException: 执行 CreateHandle() 时无法调用值 Dispose()。
   在 System.Windows.Forms.Control.Dispose(Boolean disposing)
   在 System.ComponentModel.Component.Dispose()
   在 System.Windows.Forms.Control.Dispose(Boolean disposing)
   在 V2RayGCon.Views.UserControls.SubscriptionUI.Dispose(Boolean disposing) 位置 D:\a\V2RayGCon\V2RayGCon\V2RayGCon\Views\UserControls\SubscriptionUI.Designer.cs:行号 20
   在 System.ComponentModel.Component.Dispose()
   在 System.Windows.Forms.Control.Dispose(Boolean disposing)
   在 System.ComponentModel.Component.Dispose()
   在 System.Windows.Forms.Control.Dispose(Boolean disposing)
   在 System.ComponentModel.Component.Dispose()
   在 System.Windows.Forms.Control.Dispose(Boolean disposing)
   在 System.ComponentModel.Component.Dispose()
   在 System.Windows.Forms.Control.Dispose(Boolean disposing)
   在 System.Windows.Forms.Form.Dispose(Boolean disposing)
   在 System.Windows.Forms.Form.WmClose(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by vrnobody** [comment]
这个bug在选项窗口还没加载完就点关闭时会出现。不过在`v1.2.7.12`已经修过一次了，下个版本将再修一下。临时解决办法是等选项窗口加载完再点关闭。
