### ISSUE TITLE
开启全局后，本地局域网远程连接会显示协议错误

### ISSUE THREAD

**Issue by wajika** [vrnobody/V2RayGCon#5]
这个是协议不支持吗？

**Comment by vrnobody** [comment]
windows的全局代理只支持http协议,有些软件还会忽略windows的全局设定.
不太确定你遇到了什么问题,是浏览器显示协议错误,还是某个软件,或者是v2ray-core的日志?

**Comment by wajika** [comment]
@vrnobody 远程主机开了全局后，打开mstsc，系统提示不支持的协议，然后就mstsc进程就退出了。无法进入到远程桌面

**Comment by vrnobody** [comment]
没怎么用远程主机，这个我也不知道什么问题了。
