### ISSUE TITLE
如何开启代理模式

### ISSUE THREAD

**Issue by soulxiangmu** [vrnobody/V2RayGCon#8]
研究了半天，找不到怎样开启代理模式

**Comment by vrnobody** [comment]
代理模式要启用ProxySetter插件后才可以使用
[插件开启方法](https://vrnobody.github.io/V2RayGCon/03-plugins/)
[ProxySetter插件详细用法](https://vrnobody.github.io/V2RayGCon/03-plugins/03-proxysetter/)

注：以前试过默认开启ProxySetter插件，但是Microsoft Defender会报毒，所以只好改成让用户手动开。

**Comment by soulxiangmu** [comment]
> 代理模式要启用ProxySetter插件后才可以使用
> [插件开启方法](https://vrnobody.github.io/V2RayGCon/03-plugins/)
> [ProxySetter插件详细用法](https://vrnobody.github.io/V2RayGCon/03-plugins/03-proxysetter/)
> 
> 注：以前试过默认开启ProxySetter插件，但是Microsoft Defender会报毒，所以只好改成让用户手动开。

原来如此，建议这个加在文档最前面吧，第一次用这个真的很抓狂，找来找去都找不到哪里有代理模式。

**Comment by vrnobody** [comment]
已添加相关文档，谢谢反馈。
